"use strict";
const { logToChannel } = require('./logger.js');
const { COLORS } = require('./componentBuilder.js');

function clip(value, max=1000){ if(value == null) return '-'; const s=String(value); return s.length>max ? `${s.slice(0,max-3)}...` : s; }
async function audit(client,guildId,title,data,color=COLORS.default){
  if(!guildId) return;
  await logToChannel(client,guildId,'audit',title,data,color).catch(err=>console.error('[AUDIT]',err.message));
}
async function command(client,interaction){
  const data={Command:`/${interaction.commandName}`,User:`${interaction.user.tag} (${interaction.user.id})`,Channel:interaction.channelId?`<#${interaction.channelId}>`:'-',Options:'-'};
  try{ const opts=interaction.options?.data||[]; if(opts.length) data.Options=clip(JSON.stringify(opts.map(o=>({name:o.name,value:o.value||null,user:o.user?.id,channel:o.channel?.id,role:o.role?.id})))); }catch{}
  await audit(client,interaction.guildId,'Command Used',data);
}
async function messageBulkDelete(client,messages){ const first=messages?.first?.(); if(!first?.guild)return; await audit(client,first.guild.id,'Messages Bulk Deleted',{Count:String(messages.size),Channel:first.channelId?`<#${first.channelId}>`:'Unknown'},COLORS.warning); }
async function messageDelete(client,message){ if(!message.guild) return; await audit(client,message.guild.id,'Message Deleted',{User:message.author?`${message.author.tag} (${message.author.id})`:'Unknown',Channel:`<#${message.channelId}>`,Content:clip(message.content||'[No content]')},COLORS.warning); }
async function messageUpdate(client,oldMessage,newMessage){ if(!newMessage.guild) return; if(oldMessage.content===newMessage.content) return; await audit(client,newMessage.guild.id,'Message Edited',{User:newMessage.author?`${newMessage.author.tag} (${newMessage.author.id})`:'Unknown',Channel:`<#${newMessage.channelId}>`,Before:clip(oldMessage.content||'[No content]'),After:clip(newMessage.content||'[No content]')},COLORS.default); }
async function roleCreate(client,role){ await logToChannel(client,role.guild.id,'role','Role Created',{Role:`@${role.name} (${role.id})`,Position:role.position}); }
async function roleDelete(client,role){ await logToChannel(client,role.guild.id,'role','Role Deleted',{Role:`${role.name} (${role.id})`},COLORS.warning); }
async function roleUpdate(client,oldRole,newRole){ const changes=[]; if(oldRole.name!==newRole.name)changes.push(`Name: ${oldRole.name} -> ${newRole.name}`); if(oldRole.permissions.bitfield!==newRole.permissions.bitfield)changes.push('Permissions changed'); if(oldRole.position!==newRole.position)changes.push(`Position: ${oldRole.position} -> ${newRole.position}`); if(oldRole.hexColor!==newRole.hexColor)changes.push(`Color: ${oldRole.hexColor} -> ${newRole.hexColor}`); if(!changes.length)return; await logToChannel(client,newRole.guild.id,'role','Role Updated',{Role:`@${newRole.name} (${newRole.id})`,Changes:clip(changes.join(' | '))}); }
async function memberUpdate(client,oldMember,newMember){ const added=newMember.roles.cache.filter(r=>!oldMember.roles.cache.has(r.id)).map(r=>r.name); const removed=oldMember.roles.cache.filter(r=>!newMember.roles.cache.has(r.id)).map(r=>r.name); if(added.length||removed.length){ await audit(client,newMember.guild.id,'Member Roles Updated',{User:`${newMember.user.tag} (${newMember.id})`,Added:added.join(', ')||'None',Removed:removed.join(', ')||'None'}); } if(oldMember.nickname!==newMember.nickname){await audit(client,newMember.guild.id,'Member Nickname Updated',{User:`${newMember.user.tag} (${newMember.id})`,Before:oldMember.nickname||newMember.user.username,After:newMember.nickname||newMember.user.username});}}
async function memberJoin(client,member){ await audit(client,member.guild.id,'Member Joined',{User:`${member.user.tag} (${member.id})`,AccountCreated:member.user.createdAt.toUTCString(),MemberCount:member.guild.memberCount},COLORS.success); }
async function memberLeave(client,member){ await audit(client,member.guild.id,'Member Left',{User:`${member.user?.tag||'Unknown'} (${member.id})`,MemberCount:member.guild.memberCount},COLORS.warning); }
async function banAdd(client,ban){ await audit(client,ban.guild.id,'User Banned',{User:`${ban.user.tag} (${ban.user.id})`,Reason:ban.reason||'Not provided'},COLORS.danger); }
async function banRemove(client,ban){ await audit(client,ban.guild.id,'User Unbanned',{User:`${ban.user.tag} (${ban.user.id})`,Reason:ban.reason||'Not provided'},COLORS.success); }
async function channelCreate(client,channel){ if(!channel.guild)return; await logToChannel(client,channel.guild.id,'channel','Channel Created',{Channel:`<#${channel.id}>`,Name:channel.name,Type:String(channel.type)}); }
async function channelDelete(client,channel){ if(!channel.guild)return; await logToChannel(client,channel.guild.id,'channel','Channel Deleted',{Channel:channel.name||channel.id,Type:String(channel.type)},COLORS.warning); }
async function channelUpdate(client,oldChannel,newChannel){ if(!newChannel.guild)return; const changes=[]; if(oldChannel.name!==newChannel.name)changes.push(`Name: ${oldChannel.name} -> ${newChannel.name}`); if(oldChannel.parentId!==newChannel.parentId)changes.push('Category changed'); if(oldChannel.rateLimitPerUser!==newChannel.rateLimitPerUser)changes.push(`Slowmode: ${oldChannel.rateLimitPerUser||0} -> ${newChannel.rateLimitPerUser||0}`); if(!changes.length)return; await logToChannel(client,newChannel.guild.id,'channel','Channel Updated',{Channel:`<#${newChannel.id}>`,Changes:changes.join(' | ')}); }
async function voice(client,oldState,newState){ if(oldState.channelId===newState.channelId&&oldState.serverMute===newState.serverMute&&oldState.serverDeaf===newState.serverDeaf)return; const member=newState.member||oldState.member; if(!member?.guild)return; await logToChannel(client,member.guild.id,'voice','Voice State Updated',{User:`${member.user.tag} (${member.id})`,Before:oldState.channelId?`<#${oldState.channelId}>`:'None',After:newState.channelId?`<#${newState.channelId}>`:'None',ServerMute:newState.serverMute?'Yes':'No',ServerDeaf:newState.serverDeaf?'Yes':'No'}); }
async function webhook(client,guild){ await audit(client,guild.id,'Webhook Updated',{Channels: 'Webhook configuration changed'}); }
async function guildUpdate(client,oldGuild,newGuild){ const changes=[]; if(oldGuild.name!==newGuild.name)changes.push(`Name: ${oldGuild.name} -> ${newGuild.name}`); if(oldGuild.icon!==newGuild.icon)changes.push('Icon changed'); if(changes.length) await audit(client,newGuild.id,'Server Updated',{Changes:changes.join(' | ')}); }
module.exports={audit,command,messageDelete,messageBulkDelete,messageUpdate,roleCreate,roleDelete,roleUpdate,memberUpdate,memberJoin,memberLeave,banAdd,banRemove,channelCreate,channelDelete,channelUpdate,voice,webhook,guildUpdate};
