"use strict";
const {EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,ChannelSelectMenuBuilder,StringSelectMenuBuilder,ChannelType,MessageFlags}=require('discord.js');
const GuildSettings=require('../db/models/GuildSettings.js');
async function get(guildId){return GuildSettings.findOneAndUpdate({guildId},{$setOnInsert:{guildId}},{upsert:true,new:true,setDefaultsOnInsert:true});}
const MAP={command:'commandLogChannelId',message:'messageLogChannelId',member:'memberLogChannelId',role:'roleLogChannelId',channel:'channelLogChannelId',voice:'voiceLogChannelId',security:'securityLogChannelId',mod:'logChannelId',audit:'auditLogChannelId'};
const LABELS={command:'Commands',message:'Messages',member:'Members',role:'Roles',channel:'Channels',voice:'Voice',security:'Security',mod:'Moderation',audit:'Audit'};
function panel(s){const values=Object.entries(LABELS).map(([k,l])=>({name:l,value:s[MAP[k]]?`<#${s[MAP[k]]}>`:'Not set',inline:true}));return {embeds:[new EmbedBuilder().setTitle('Logging Configuration').setDescription('Select a log category, then choose its channel.').addFields(values).setColor(0x5865f2)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('logs_toggle').setLabel(s.loggingEnabled?'Disable Logging':'Enable Logging').setStyle(s.loggingEnabled?ButtonStyle.Danger:ButtonStyle.Success),new ButtonBuilder().setCustomId('logs_clear').setLabel('Clear All').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId('logs_refresh').setLabel('Refresh').setStyle(ButtonStyle.Secondary)),new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('logs_pick_category').setPlaceholder('Select a log category').addOptions(Object.entries(LABELS).map(([v,l])=>({label:l,value:v}))))],flags:MessageFlags.Ephemeral};}
async function handle(i){if(!(await require('./permissionChecker.js').hasPermission(i.member,'manageGuild')))return i.reply({content:'Manage Server permission is required.',flags:64});return i.reply(panel(await get(i.guildId)));}
async function component(i){if(!(await require('./permissionChecker.js').hasPermission(i.member,'manageGuild')))return i.reply({content:'Manage Server permission is required.',flags:64});const s=await get(i.guildId);if(i.customId==='logs_toggle'){s.loggingEnabled=!s.loggingEnabled;await s.save();return i.update(panel(s));}if(i.customId==='logs_clear'){for(const k of Object.values(MAP))s[k]=null;await s.save();return i.update(panel(s));}if(i.customId==='logs_refresh')return i.update(panel(s));if(i.customId==='logs_pick_category'&&i.isStringSelectMenu()){const k=i.values[0];const label=LABELS[k];return i.update({embeds:[new EmbedBuilder().setTitle(`Set ${label} Log Channel`).setDescription(`Select the channel for ${label.toLowerCase()} logs.`)],components:[new ActionRowBuilder().addComponents(new ChannelSelectMenuBuilder().setCustomId(`logs_set_${k}`).setPlaceholder(`Select ${label.toLowerCase()} log channel`).setChannelTypes(ChannelType.GuildText,ChannelType.GuildAnnouncement)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('logs_back').setLabel('Back').setStyle(ButtonStyle.Secondary))],flags:64});}if(i.customId==='logs_back')return i.update(panel(s));if(i.isChannelSelectMenu()&&i.customId.startsWith('logs_set_')){const k=i.customId.replace('logs_set_','');if(!MAP[k])return i.reply({content:'Unknown log category.',flags:64});s[MAP[k]]=i.values[0];await s.save();return i.update(panel(s));}}
module.exports={get,panel,handle,component,MAP};
