"use strict";
const {
  ActionRowBuilder, ButtonBuilder, ButtonStyle, UserSelectMenuBuilder, StringSelectMenuBuilder, ChannelType, ModalBuilder,
  TextInputBuilder, TextInputStyle, MessageFlags
} = require('discord.js');
const { createMessage, createActionRow, createButton, COLORS } = require('./componentBuilder.js');
const OwnerConfig = require('../db/models/OwnerConfig.js');
const GlobalEntry = require('../db/models/GlobalEntry.js');
const SecurityReport = require('../db/models/SecurityReport.js');
const { getOwnerConfig, isOwner, hasGlobalPermission, auditDatabase } = require('./ownerConfig.js');

function ownerPanel(cfg, client) {
  const main = cfg.mainGuildId ? client.guilds.cache.get(cfg.mainGuildId) : null;
  const channel = cfg.channels.securityReports ? `<#${cfg.channels.securityReports}>` : 'Not set';
  const dbChannel = cfg.channels.databaseAudit ? `<#${cfg.channels.databaseAudit}>` : 'Not set';
  return createMessage({ title: ' LXCKY SECURITY - OWNER PANEL', data: {
    'Main Guild': main ? `${main.name} (${main.id})` : 'Not configured',
    'Security Reports': channel,
    'Database Audit': dbChannel,
    'Trusted Staff': `${cfg.trustedStaff.length}`,
    'Global Database': 'Owner-controlled'
  }, color: COLORS.default, components: [
    createActionRow(createButton({label:' Channels',customId:'owner_channels',style:'primary'}),createButton({label:' Trusted Staff',customId:'owner_staff',style:'primary'}),createButton({label:' Database',customId:'owner_database',style:'primary'})),
    createActionRow(createButton({label:' Reports',customId:'owner_reports',style:'danger'}),createButton({label:' Statistics',customId:'owner_stats',style:'secondary'}),createButton({label:' Servers',customId:'owner_servers',style:'secondary'})),
    createActionRow(createButton({label:' Health',customId:'owner_health',style:'secondary'}),createButton({label:' Leave Server',customId:'owner_leave_server',style:'danger'}),createButton({label:' Refresh',customId:'owner_refresh',style:'secondary'}))
  ], ephemeral: true });
}
function channelsPanel(cfg) {
  const labels = {databaseAudit:'Database Audit',securityReports:'Security Reports',botJoins:'Bot Join Reports',globalAlerts:'Global Alerts',antiNuke:'Anti-Nuke Alerts',antiRaid:'Anti-Raid Alerts',securityLogs:'Security Logs',errors:'Error/Health Alerts'};
  const data = {}; for (const [k,v] of Object.entries(labels)) data[v] = cfg.channels[k] ? `<#${cfg.channels[k]}>` : 'Not set';
  const select = new StringSelectMenuBuilder().setCustomId('owner_channel_pick').setPlaceholder('Choose a channel setting').addOptions(Object.entries(labels).map(([value,label])=>({label,value,description:`Set ${label}`})));
  return createMessage({title:' Owner - Channel Configuration',data,color:COLORS.default,components:[new ActionRowBuilder().addComponents(select),createActionRow(createButton({label:'Set Main Guild',customId:'owner_set_guild',style:'primary'}),createButton({label:'Back',customId:'owner_home',style:'secondary'}))],ephemeral:true});
}
function staffPanel(cfg) {
  const data = {}; for (const s of cfg.trustedStaff) data[`<@${s.userId}>`] = `DB: ${Object.entries(s.database).filter(([,v])=>v).map(([k])=>k).join(', ')||'none'} - Reports: ${Object.entries(s.reports).filter(([,v])=>v).map(([k])=>k).join(', ')||'none'}`;
  if (!Object.keys(data).length) data['Trusted Staff'] = 'None configured';
  return createMessage({title:' Owner - Trusted Staff',data,color:COLORS.default,components:[createActionRow(createButton({label:' Add / Edit Staff',customId:'owner_add_staff',style:'success'}),createButton({label:' Remove Staff',customId:'owner_remove_staff',style:'danger'})),createActionRow(createButton({label:' Edit Permissions',customId:'owner_edit_staff',style:'primary'})),createActionRow(createButton({label:'Back',customId:'owner_home',style:'secondary'}))],ephemeral:true});
}
async function databasePanel() {
 const [users,bots,blacklisted,suspicious,trusted] = await Promise.all([
  GlobalEntry.countDocuments({type:'user',active:true}),GlobalEntry.countDocuments({type:'bot',active:true}),GlobalEntry.countDocuments({status:'blacklisted',active:true}),GlobalEntry.countDocuments({status:'suspicious',active:true}),GlobalEntry.countDocuments({status:'trusted',active:true})
 ]);
 return createMessage({title:' Owner - Global Database',data:{Users:users,Bots:bots,Blacklisted:blacklisted,Suspicious:suspicious,Trusted:trusted},color:COLORS.default,components:[createActionRow(createButton({label:' Search',customId:'owner_db_search',style:'primary'}),createButton({label:' Add Entry',customId:'owner_db_add',style:'success'}),createButton({label:' Recent',customId:'owner_db_recent',style:'secondary'})),createActionRow(createButton({label:'Back',customId:'owner_home',style:'secondary'}))],ephemeral:true});
}
async function handleOwnerPanel(interaction) {
 if (!isOwner(interaction.user.id)) return interaction.reply({content:'Owner only.',ephemeral:true});
 const id=interaction.customId;
 if(id==='owner_home'||id==='owner_refresh'){return interaction.update(ownerPanel(await getOwnerConfig(),interaction.client));}
 if(id==='owner_channels') return interaction.update(channelsPanel(await getOwnerConfig()));
 if(id==='owner_staff') return interaction.update(staffPanel(await getOwnerConfig()));
 if(id==='owner_database') return interaction.update(await databasePanel());
 if(id==='owner_reports') { const open=await SecurityReport.countDocuments({status:'open'}); const today=await SecurityReport.countDocuments({createdAt:{$gte:new Date(Date.now()-86400000)}}); return interaction.update(createMessage({title:' Owner - Reports',data:{Open:open,'Last 24 Hours':today,'Channel':(await getOwnerConfig()).channels.securityReports?`<#${(await getOwnerConfig()).channels.securityReports}>`:'Not set'},color:COLORS.danger,components:[createActionRow(createButton({label:'Back',customId:'owner_home',style:'secondary'}))],ephemeral:true})); }
 if(id==='owner_stats') { const [guilds,users,bots,reports]=await Promise.all([interaction.client.guilds.fetch(),GlobalEntry.countDocuments({type:'user',active:true}),GlobalEntry.countDocuments({type:'bot',active:true}),SecurityReport.countDocuments({createdAt:{$gte:new Date(Date.now()-86400000)}})]); const main=(await getOwnerConfig()).mainGuildId; const g=main?interaction.client.guilds.cache.get(main):null; return interaction.update(createMessage({title:' Owner - Statistics',data:{Servers:guilds.size,'DB Users':users,'DB Bots':bots,'Reports Today':reports,'Main Guild Members':g?g.memberCount:'Not set'},color:COLORS.default,components:[createActionRow(createButton({label:'Back',customId:'owner_home',style:'secondary'}))],ephemeral:true})); }
 if(id==='owner_servers') return interaction.update(createMessage({title:' Owner - Servers',data:{Servers:interaction.client.guilds.cache.size,Tip:'Use the Discord server list above or add a dedicated server browser later.'},color:COLORS.default,components:[createActionRow(createButton({label:'Back',customId:'owner_home',style:'secondary'}))],ephemeral:true}));
 if(id==='owner_health') return interaction.update(createMessage({title:' Owner - Health',data:{Discord:interaction.client.ws.status===0?' Ready':' Connecting',MongoDB:require('mongoose').connection.readyState===1?' Connected':' Disconnected',Uptime:`${Math.floor(process.uptime()/3600)}h ${Math.floor(process.uptime()/60)%60}m`,Memory:`${Math.round(process.memoryUsage().rss/1024/1024)} MB`},color:COLORS.success,components:[createActionRow(createButton({label:'Back',customId:'owner_home',style:'secondary'}))],ephemeral:true}));
 if(id==='owner_leave_server') { const modal=new ModalBuilder().setCustomId('owner_leave_server_modal').setTitle('Leave Discord Server'); modal.addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('guildId').setLabel('Server ID').setStyle(TextInputStyle.Short).setRequired(true).setMinLength(17).setMaxLength(20))); return interaction.showModal(modal); }
 if(id==='owner_set_guild') { const options=interaction.client.guilds.cache.map(g=>({label:g.name.slice(0,100),value:g.id,description:`${g.memberCount||0} members`})).slice(0,25); const menu=new StringSelectMenuBuilder().setCustomId('owner_main_guild').setPlaceholder('Select your main/central guild').addOptions(options); return interaction.update(createMessage({title:' Select Main Guild',data:{Current:(await getOwnerConfig()).mainGuildId||'Not set'},color:COLORS.default,components:[new ActionRowBuilder().addComponents(menu),createActionRow(createButton({label:'Back',customId:'owner_channels',style:'secondary'}))],ephemeral:true})); }
 if(id==='owner_channel_pick'){const key=interaction.values[0]; const cfg=await getOwnerConfig(); const guild=cfg.mainGuildId?interaction.client.guilds.cache.get(cfg.mainGuildId):null; if(!guild)return interaction.reply({content:'Set your main guild first.',ephemeral:true}); const channels=guild.channels.cache.filter(c=>c.isTextBased()&&[0,5].includes(c.type)).first(25); const menu=new StringSelectMenuBuilder().setCustomId(`owner_channel_set_${key}`).setPlaceholder(`Select ${key} channel`).addOptions(channels.map(c=>({label:c.name.slice(0,100),value:c.id,description:`#${c.name}`}))); return interaction.update(createMessage({title:' Select Channel',data:{Setting:key,Guild:guild.name},color:COLORS.default,components:[new ActionRowBuilder().addComponents(menu),createActionRow(createButton({label:'Back',customId:'owner_channels',style:'secondary'}))],ephemeral:true}));}
 if(id.startsWith('owner_channel_set_')){const key=id.replace('owner_channel_set_',''); const cfg=await getOwnerConfig(); cfg.channels[key]=interaction.values[0]; await cfg.save(); return interaction.update(channelsPanel(cfg));}
 if(id==='owner_main_guild'){const cfg=await getOwnerConfig(); cfg.mainGuildId=interaction.values[0]; await cfg.save(); return interaction.update(channelsPanel(cfg));}
 if(id==='owner_add_staff'){const menu=new UserSelectMenuBuilder().setCustomId('owner_staff_user').setPlaceholder('Select a trusted staff member'); return interaction.update(createMessage({title:' Add / Edit Trusted Staff',data:{Message:'Select one user. They will receive safe report/search access by default.'},color:COLORS.default,components:[new ActionRowBuilder().addComponents(menu),createActionRow(createButton({label:'Back',customId:'owner_staff',style:'secondary'}))],ephemeral:true}));}
 if(id==='owner_remove_staff'){const menu=new UserSelectMenuBuilder().setCustomId('owner_staff_remove').setPlaceholder('Select staff to remove'); return interaction.update(createMessage({title:' Remove Trusted Staff',data:{Message:'Select the user to remove from the global trust list.'},color:COLORS.danger,components:[new ActionRowBuilder().addComponents(menu),createActionRow(createButton({label:'Back',customId:'owner_staff',style:'secondary'}))],ephemeral:true}));}
 if(id.startsWith('owner_staff_perms_')){const uid=id.replace('owner_staff_perms_',''); const cfg=await getOwnerConfig(); const s=cfg.trustedStaff.find(x=>x.userId===uid); if(!s)return interaction.reply({content:'Staff member not found.',ephemeral:true}); const data={}; for(const [k,v] of Object.entries(s.database)) data[`DB - ${k}`]=v?'ON':'OFF'; for(const [k,v] of Object.entries(s.reports)) data[`Reports - ${k}`]=v?'ON':'OFF'; const menu=new StringSelectMenuBuilder().setCustomId(`owner_staff_perm_pick_${uid}`).setPlaceholder('Toggle a permission').addOptions([...Object.keys(s.database).map(k=>({label:`DB: ${k}`,value:`db:${k}`})),...Object.keys(s.reports).map(k=>({label:`Reports: ${k}`,value:`reports:${k}`}))]); return interaction.update(createMessage({title:` Permissions - <@${uid}>`,data,color:COLORS.default,components:[new ActionRowBuilder().addComponents(menu),createActionRow(createButton({label:'Back',customId:'owner_staff',style:'secondary'}))],ephemeral:true}));}
 if(id==='owner_db_search'){const modal=new ModalBuilder().setCustomId('owner_db_search_modal').setTitle('Search Global Database'); modal.addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('id').setLabel('Discord User/Bot ID').setStyle(TextInputStyle.Short).setRequired(true).setMinLength(17).setMaxLength(20))); return interaction.showModal(modal);}
 if(id==='owner_db_add'){const modal=new ModalBuilder().setCustomId('owner_db_add_modal').setTitle('Add Global Database Entry'); for(const [cid,label,style] of [['id','Discord ID',TextInputStyle.Short],['type','Type: user or bot',TextInputStyle.Short],['status','Status: trusted, suspicious, blacklisted',TextInputStyle.Short],['reason','Reason',TextInputStyle.Paragraph]]) modal.addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId(cid).setLabel(label).setStyle(style).setRequired(true))); return interaction.showModal(modal);}
 if(id==='owner_db_recent'){const rows=await GlobalEntry.find({active:true}).sort({updatedAt:-1}).limit(8); return interaction.update(createMessage({title:' Recent Database Entries',data:rows.length?Object.fromEntries(rows.map((r,i)=>[`${i+1}. ${r.discordId}`,`${r.type} - ${r.status} - ${r.reason}`])):{'Database':'No entries'},color:COLORS.default,components:[createActionRow(createButton({label:'Back',customId:'owner_database',style:'secondary'}))],ephemeral:true}));}
}
async function handleOwnerSelect(interaction){
 if(!isOwner(interaction.user.id)) return interaction.reply({content:'Owner only.',ephemeral:true});
 if(interaction.isStringSelectMenu() && interaction.customId==='owner_main_guild'){const cfg=await getOwnerConfig();cfg.mainGuildId=interaction.values[0];await cfg.save();return interaction.update(channelsPanel(cfg));}
 if(interaction.isStringSelectMenu() && interaction.customId==='owner_channel_pick'){const key=interaction.values[0];const cfg=await getOwnerConfig();const guild=cfg.mainGuildId?interaction.client.guilds.cache.get(cfg.mainGuildId):null;if(!guild)return interaction.reply({content:'Set your main guild first.',ephemeral:true});const channels=guild.channels.cache.filter(c=>c.isTextBased()&&[0,5].includes(c.type)).first(25);if(!channels.length)return interaction.reply({content:'No text channels found in the main guild.',ephemeral:true});const menu=new StringSelectMenuBuilder().setCustomId(`owner_channel_set_${key}`).setPlaceholder(`Select ${key} channel`).addOptions(channels.map(c=>({label:c.name.slice(0,100),value:c.id,description:`#${c.name}`})));return interaction.update(createMessage({title:' Select Channel',data:{Setting:key,Guild:guild.name},color:COLORS.default,components:[new ActionRowBuilder().addComponents(menu),createActionRow(createButton({label:'Back',customId:'owner_channels',style:'secondary'}))],ephemeral:true}));}
 if(interaction.isStringSelectMenu() && interaction.customId.startsWith('owner_channel_set_')){const key=interaction.customId.replace('owner_channel_set_','');const cfg=await getOwnerConfig();if(!(key in cfg.channels))return interaction.reply({content:'Invalid channel setting.',ephemeral:true});cfg.channels[key]=interaction.values[0];await cfg.save();return interaction.update(channelsPanel(cfg));}
 if(interaction.customId==='owner_edit_staff'){const menu=new UserSelectMenuBuilder().setCustomId('owner_staff_edit').setPlaceholder('Select staff member'); return interaction.update(createMessage({title:' Edit Staff Permissions',data:{Message:'Select a trusted staff member.'},color:COLORS.default,components:[new ActionRowBuilder().addComponents(menu),createActionRow(createButton({label:'Back',customId:'owner_staff',style:'secondary'}))],ephemeral:true}));}
 if(interaction.customId==='owner_staff_user'){const uid=interaction.values[0]; const cfg=await getOwnerConfig(); let s=cfg.trustedStaff.find(x=>x.userId===uid); if(!s){cfg.trustedStaff.push({userId:uid}); await cfg.save();} return interaction.update(staffPanel(cfg));}
 if(interaction.customId==='owner_staff_edit'){const uid=interaction.values[0]; return interaction.update(await buildStaffPermissionPanel(uid));}
 if(interaction.customId.startsWith('owner_staff_perm_pick_')){const uid=interaction.customId.replace('owner_staff_perm_pick_',''); const [group,key]=interaction.values[0].split(':'); const cfg=await getOwnerConfig(); const s=cfg.trustedStaff.find(x=>x.userId===uid); if(!s)return interaction.reply({content:'Staff member not found.',ephemeral:true}); s[group][key]=!s[group][key]; await cfg.save(); return interaction.update(await buildStaffPermissionPanel(uid));}
 if(interaction.customId==='owner_staff_remove'){const uid=interaction.values[0]; const cfg=await getOwnerConfig(); cfg.trustedStaff=cfg.trustedStaff.filter(x=>x.userId!==uid); await cfg.save(); return interaction.update(staffPanel(cfg));}
}
async function handleOwnerModal(interaction){
 if(!isOwner(interaction.user.id)) return interaction.reply({content:'Owner only.',flags:64});
 if(interaction.customId==='owner_leave_server_modal'){ const id=interaction.fields.getTextInputValue('guildId').trim(); const guild=interaction.client.guilds.cache.get(id); if(!guild) return interaction.reply({content:'The bot is not in that server.',flags:64}); const name=guild.name; await guild.leave(); return interaction.reply({content:`Left ${name} (${id}).`,flags:64}); }
 if(interaction.customId==='owner_db_search_modal'){const id=interaction.fields.getTextInputValue('id').trim(); const entry=await GlobalEntry.findOne({discordId:id,active:true}); return interaction.reply(entry?createMessage({title:' Database Result',data:{ID:entry.discordId,Type:entry.type,Status:entry.status,Reason:entry.reason,'Added By':`<@${entry.addedBy}>`,Created:entry.createdAt.toUTCString()},color:entry.status==='blacklisted'?COLORS.danger:COLORS.default,ephemeral:true}):createMessage({title:' Database Result',data:{Status:' Not Found',ID:id,Message:'This ID is not currently in the global database.'},color:COLORS.warning,ephemeral:true}));}
 if(interaction.customId==='owner_db_add_modal'){const cfg=await getOwnerConfig();const id=interaction.fields.getTextInputValue('id').trim();const type=interaction.fields.getTextInputValue('type').trim().toLowerCase();const status=interaction.fields.getTextInputValue('status').trim().toLowerCase();const reason=interaction.fields.getTextInputValue('reason').trim();if(!/^\d{17,20}$/.test(id)||!['user','bot'].includes(type)||!['trusted','suspicious','blacklisted'].includes(status)) return interaction.reply({content:'Invalid ID, type, or status.',flags:64});let e=await GlobalEntry.findOne({discordId:id});const action=e&&e.active?'UPDATE':'ADD';if(e){e.type=type;e.status=status;e.reason=reason;e.updatedBy=interaction.user.id;e.active=true;}else e=new GlobalEntry({discordId:id,type,status,reason,addedBy:interaction.user.id,updatedBy:interaction.user.id,active:true});await e.save();await auditDatabase({action,discordId:id,type,status,reason,actorId:interaction.user.id,sourceGuildId:cfg.mainGuildId});return interaction.reply(createMessage({title:' Database Updated',data:{ID:id,Type:type,Status:status,Reason:reason},color:COLORS.success,ephemeral:true}));}
}
async function buildStaffPermissionPanel(uid){const cfg=await getOwnerConfig();const s=cfg.trustedStaff.find(x=>x.userId===uid);return createMessage({title:` Permissions - <@${uid}>`,data:{'DB Search':s?.database.search?'ON':'OFF','DB View':s?.database.view?'ON':'OFF','DB Add':s?.database.add?'ON':'OFF','DB Edit':s?.database.edit?'ON':'OFF','DB Remove':s?.database.remove?'ON':'OFF','DB Status':s?.database.status?'ON':'OFF','Reports View':s?.reports.view?'ON':'OFF','Reports Investigate':s?.reports.investigate?'ON':'OFF','Reports Resolve':s?.reports.resolve?'ON':'OFF'},color:COLORS.default,components:[createActionRow(createButton({label:'Toggle Search',customId:`owner_staff_perms_${uid}`,style:'primary'}),createButton({label:'Back',customId:'owner_staff',style:'secondary'}))],ephemeral:true});}

module.exports={ownerPanel,handleOwnerPanel,handleOwnerSelect,handleOwnerModal};
