"use strict";
const { EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, ChannelSelectMenuBuilder, RoleSelectMenuBuilder, StringSelectMenuBuilder, ChannelType, MessageFlags } = require('discord.js');
const VerificationConfig=require('../db/models/VerificationConfig.js');
const { logVerify }=require('./logger.js');

async function getConfig(guildId){return VerificationConfig.findOneAndUpdate({guildId},{$setOnInsert:{guildId}},{upsert:true,new:true,setDefaultsOnInsert:true});}

function setupPanel(cfg){
  const visible=(cfg.visibleChannelIds||[]).map(id=>`<#${id}>`).join(', ')||'None';
  const hidden=(cfg.hiddenChannelIds||[]).map(id=>`<#${id}>`).join(', ')||'None';
  const embed=new EmbedBuilder().setTitle('Verification Setup').setDescription('Configure verification once. Settings are saved in MongoDB.').setColor(0x5865f2).addFields(
    {name:'Enabled',value:cfg.enabled?'Yes':'No',inline:true},
    {name:'Verification Channel',value:cfg.verificationChannelId?`<#${cfg.verificationChannelId}>`:'Not set',inline:true},
    {name:'Verified Role',value:cfg.verifiedRoleId?`<@&${cfg.verifiedRoleId}>`:'Not set',inline:true},
    {name:'Unverified Role',value:cfg.unverifiedRoleId?`<@&${cfg.unverifiedRoleId}>`:'Not set',inline:true},
    {name:'Log Channel',value:cfg.logChannelId?`<#${cfg.logChannelId}>`:'Not set',inline:true},
    {name:'Visible Before Verification',value:visible.slice(0,1024)},
    {name:'Hidden Before Verification',value:hidden.slice(0,1024)}
  );
  return {embeds:[embed],components:[
    new ActionRowBuilder().addComponents(
      new ButtonBuilder().setCustomId('verify_pick_channel').setLabel('Verification Channel').setStyle(ButtonStyle.Primary),
      new ButtonBuilder().setCustomId('verify_pick_verified').setLabel('Verified Role').setStyle(ButtonStyle.Primary),
      new ButtonBuilder().setCustomId('verify_pick_unverified').setLabel('Unverified Role').setStyle(ButtonStyle.Primary),
      new ButtonBuilder().setCustomId('verify_pick_visible').setLabel('Visible Channels').setStyle(ButtonStyle.Secondary),
      new ButtonBuilder().setCustomId('verify_pick_hidden').setLabel('Hidden Channels').setStyle(ButtonStyle.Secondary)
    ),
    new ActionRowBuilder().addComponents(
      new ButtonBuilder().setCustomId('verify_pick_log').setLabel('Log Channel').setStyle(ButtonStyle.Secondary),
      new ButtonBuilder().setCustomId('verify_toggle').setLabel(cfg.enabled?'Disable':'Enable').setStyle(cfg.enabled?ButtonStyle.Danger:ButtonStyle.Success),
      new ButtonBuilder().setCustomId('verify_apply').setLabel('Apply Permissions').setStyle(ButtonStyle.Success),
      new ButtonBuilder().setCustomId('verify_post').setLabel('Post Panel').setStyle(ButtonStyle.Primary),
      new ButtonBuilder().setCustomId('verify_refresh').setLabel('Refresh').setStyle(ButtonStyle.Secondary)
    )
  ],flags:MessageFlags.Ephemeral};
}
function publicPanel(cfg){return {embeds:[new EmbedBuilder().setTitle(cfg.messageTitle||'Verification').setDescription(cfg.messageDescription||'Verify to access the server.').setColor(0x57f287)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('verify_user').setLabel(cfg.buttonLabel||'Verify').setStyle(ButtonStyle.Success))]};}
function expandSelectedChannels(guild,ids){const out=new Map();for(const id of ids||[]){const ch=guild.channels.cache.get(id);if(!ch)continue;out.set(ch.id,ch);if(ch.type===ChannelType.GuildCategory)for(const child of guild.channels.cache.values())if(child.parentId===ch.id)out.set(child.id,child);}return [...out.values()];}
async function applyPermissions(guild,cfg){const role=cfg.unverifiedRoleId?guild.roles.cache.get(cfg.unverifiedRoleId):null;if(!role)throw new Error('Set an unverified role first.');const targets=expandSelectedChannels(guild,[...(cfg.visibleChannelIds||[]),...(cfg.hiddenChannelIds||[])]);const hidden=new Set(expandSelectedChannels(guild,cfg.hiddenChannelIds||[]).map(c=>c.id));const snapshots=cfg.snapshots||{};for(const ch of targets){const existing=ch.permissionOverwrites.cache.get(role.id);if(!snapshots[ch.id])snapshots[ch.id]={view:existing?.allow?.has('ViewChannel')?'allow':existing?.deny?.has('ViewChannel')?'deny':'none'};await ch.permissionOverwrites.edit(role,{ViewChannel:!hidden.has(ch.id)},{reason:'Verification system configuration'}).catch(()=>{});}cfg.snapshots=snapshots;await cfg.save();return targets.length;}
async function restorePermissions(guild,cfg){const role=cfg.unverifiedRoleId?guild.roles.cache.get(cfg.unverifiedRoleId):null;if(!role)return 0;let restored=0;for(const [id,state] of Object.entries(cfg.snapshots||{})){const ch=guild.channels.cache.get(id);if(!ch?.permissionOverwrites)continue;const value=state.view==='allow'?true:state.view==='deny'?false:null;await ch.permissionOverwrites.edit(role,{ViewChannel:value},{reason:'Verification permissions restored'}).catch(()=>{});restored++;}cfg.snapshots={};await cfg.save();return restored;}
async function ensureUnverified(member,cfg){if(!cfg.enabled||!cfg.unverifiedRoleId||member.user.bot)return;const role=member.guild.roles.cache.get(cfg.unverifiedRoleId);if(role)await member.roles.add(role,'Verification pending').catch(()=>{});}
async function verifyMember(interaction,cfg){const member=interaction.member;const verified=cfg.verifiedRoleId?interaction.guild.roles.cache.get(cfg.verifiedRoleId):null;const unverified=cfg.unverifiedRoleId?interaction.guild.roles.cache.get(cfg.unverifiedRoleId):null;if(!cfg.enabled)return interaction.reply({content:'Verification is currently disabled.',flags:64});if(!verified)return interaction.reply({content:'Verification is not configured yet.',flags:64});if(unverified&&member.roles.cache.has(unverified.id))await member.roles.remove(unverified,'Member verified').catch(()=>{});await member.roles.add(verified,'Member verified').catch(()=>{});if(cfg.logChannelId)await logVerify(interaction.client,interaction.guildId,'User Verified',{User:`${interaction.user.tag} (${interaction.user.id})`,Channel:`<#${interaction.channelId}>`});return interaction.reply({content:'You are now verified.',flags:64});}
async function handle(interaction){const cfg=await getConfig(interaction.guildId);const sub=interaction.options.getSubcommand();if(sub==='setup')return interaction.reply(setupPanel(cfg));if(sub==='panel')return interaction.reply(publicPanel(cfg));const user=interaction.options.getUser('target',true);const member=await interaction.guild.members.fetch(user.id).catch(()=>null);if(!member)return interaction.reply({content:'Member not found.',flags:64});const verified=cfg.verifiedRoleId?interaction.guild.roles.cache.get(cfg.verifiedRoleId):null;if(!verified)return interaction.reply({content:'Verification is not configured yet.',flags:64});await member.roles.add(verified,'Manual verification').catch(()=>{});if(cfg.unverifiedRoleId)await member.roles.remove(cfg.unverifiedRoleId,'Manual verification').catch(()=>{});if(cfg.logChannelId)await logVerify(interaction.client,interaction.guildId,'User Verified',{User:`${user.tag} (${user.id})`,By:`<@${interaction.user.id}>`,Manual:'Yes'});return interaction.reply({content:`Verified <@${user.id}>.`,flags:64});}
async function component(interaction){const cfg=await getConfig(interaction.guildId);const id=interaction.customId;
 if(id==='verify_user')return verifyMember(interaction,cfg);
 if(id==='verify_refresh')return interaction.update(setupPanel(cfg));
 if(id==='verify_toggle'){cfg.enabled=!cfg.enabled;await cfg.save();if(cfg.enabled===false&&Object.keys(cfg.snapshots||{}).length)await restorePermissions(interaction.guild,cfg);return interaction.update(setupPanel(cfg));}
 if(id==='verify_apply'){if(!interaction.deferred&&!interaction.replied) await interaction.deferReply({flags:64});try{const n=cfg.enabled?await applyPermissions(interaction.guild,cfg):await restorePermissions(interaction.guild,cfg);return interaction.editReply({content:`Verification permissions updated for ${n} channel(s).`});}catch(e){console.error('[VERIFICATION] Apply failed:',e);return interaction.editReply({content:e.message||'Failed to apply verification permissions.'});}}
 if(id==='verify_post'){if(!cfg.verificationChannelId)return interaction.reply({content:'Set a verification channel first.',flags:64});const ch=interaction.guild.channels.cache.get(cfg.verificationChannelId);if(!ch?.isTextBased())return interaction.reply({content:'Verification channel is invalid.',flags:64});if(!interaction.deferred&&!interaction.replied) await interaction.deferReply({flags:64});try{await ch.send(publicPanel(cfg));return interaction.editReply({content:`Verification panel posted in <#${ch.id}>.`});}catch(error){console.error('[VERIFICATION] Post failed:',error);return interaction.editReply({content:'Failed to post the verification panel.'});}}
 if(id==='verify_pick_channel')return interaction.update({embeds:[new EmbedBuilder().setTitle('Verification Channel').setDescription('Select the channel where the verification panel should be posted.')],components:[new ActionRowBuilder().addComponents(new ChannelSelectMenuBuilder().setCustomId('verify_set_channel').setPlaceholder('Select channel').setChannelTypes(ChannelType.GuildText,ChannelType.GuildAnnouncement)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('verify_back').setLabel('Back').setStyle(ButtonStyle.Secondary))],flags:64});
 if(id==='verify_pick_log')return interaction.update({embeds:[new EmbedBuilder().setTitle('Verification Log Channel').setDescription('Select where verification events should be logged.')],components:[new ActionRowBuilder().addComponents(new ChannelSelectMenuBuilder().setCustomId('verify_set_log').setPlaceholder('Select log channel').setChannelTypes(ChannelType.GuildText,ChannelType.GuildAnnouncement)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('verify_back').setLabel('Back').setStyle(ButtonStyle.Secondary))],flags:64});
 if(id==='verify_pick_verified')return interaction.update({embeds:[new EmbedBuilder().setTitle('Verified Role').setDescription('Select the role granted after verification.')],components:[new ActionRowBuilder().addComponents(new RoleSelectMenuBuilder().setCustomId('verify_set_verified_role').setPlaceholder('Select verified role')),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('verify_back').setLabel('Back').setStyle(ButtonStyle.Secondary))],flags:64});
 if(id==='verify_pick_unverified')return interaction.update({embeds:[new EmbedBuilder().setTitle('Unverified Role').setDescription('Select the role assigned to new unverified members.')],components:[new ActionRowBuilder().addComponents(new RoleSelectMenuBuilder().setCustomId('verify_set_unverified_role').setPlaceholder('Select unverified role')),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('verify_back').setLabel('Back').setStyle(ButtonStyle.Secondary))],flags:64});
 if(id==='verify_pick_visible')return interaction.update({embeds:[new EmbedBuilder().setTitle('Visible Before Verification').setDescription('Select channels or categories unverified users may see.')],components:[new ActionRowBuilder().addComponents(new ChannelSelectMenuBuilder().setCustomId('verify_set_visible').setPlaceholder('Select visible channels/categories').setMinValues(0).setMaxValues(25).setChannelTypes(ChannelType.GuildText,ChannelType.GuildAnnouncement,ChannelType.GuildCategory)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('verify_back').setLabel('Back').setStyle(ButtonStyle.Secondary))],flags:64});
 if(id==='verify_pick_hidden')return interaction.update({embeds:[new EmbedBuilder().setTitle('Hidden Before Verification').setDescription('Select channels or categories hidden from unverified users.')],components:[new ActionRowBuilder().addComponents(new ChannelSelectMenuBuilder().setCustomId('verify_set_hidden').setPlaceholder('Select hidden channels/categories').setMinValues(0).setMaxValues(25).setChannelTypes(ChannelType.GuildText,ChannelType.GuildAnnouncement,ChannelType.GuildCategory)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('verify_back').setLabel('Back').setStyle(ButtonStyle.Secondary))],flags:64});
 if(id==='verify_back')return interaction.update(setupPanel(cfg));
 if(id==='verify_set_channel'&&interaction.isChannelSelectMenu()){cfg.verificationChannelId=interaction.values[0];await cfg.save();return interaction.update(setupPanel(cfg));}
 if(id==='verify_set_log'&&interaction.isChannelSelectMenu()){cfg.logChannelId=interaction.values[0];await cfg.save();return interaction.update(setupPanel(cfg));}
 if(id==='verify_set_visible'&&interaction.isChannelSelectMenu()){cfg.visibleChannelIds=interaction.values||[];await cfg.save();return interaction.update(setupPanel(cfg));}
 if(id==='verify_set_hidden'&&interaction.isChannelSelectMenu()){cfg.hiddenChannelIds=interaction.values||[];await cfg.save();return interaction.update(setupPanel(cfg));}
 if(id==='verify_set_verified_role'&&interaction.isRoleSelectMenu()){cfg.verifiedRoleId=interaction.values[0];await cfg.save();return interaction.update(setupPanel(cfg));}
 if(id==='verify_set_unverified_role'&&interaction.isRoleSelectMenu()){cfg.unverifiedRoleId=interaction.values[0];await cfg.save();return interaction.update(setupPanel(cfg));}
}
module.exports={getConfig,setupPanel,publicPanel,applyPermissions,restorePermissions,ensureUnverified,verifyMember,handle,component};
