"use strict";
const {EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,UserSelectMenuBuilder,RoleSelectMenuBuilder,ChannelSelectMenuBuilder,StringSelectMenuBuilder,ChannelType}=require('discord.js');
const WhitelistEntry=require('../db/models/WhitelistEntry.js');
async function panel(guildId){const rows=await WhitelistEntry.find({guildId}).sort({createdAt:-1}).limit(20);return {embeds:[new EmbedBuilder().setTitle('Whitelist').setDescription('Users, roles, bots and channels exempted from security systems.').addFields({name:'Entries',value:rows.length?rows.map(r=>`${r.type}: <${r.type==='role'?'@&':'@'}${r.targetId}>`).join('\n').slice(0,1024):'None'})],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('whitelist_add_user').setLabel('Add User').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('whitelist_add_role').setLabel('Add Role').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('whitelist_add_channel').setLabel('Add Channel').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('whitelist_remove').setLabel('Remove').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId('whitelist_refresh').setLabel('Refresh').setStyle(ButtonStyle.Secondary))]};}
async function handle(i){if(!(await require('./permissionChecker.js').hasPermission(i.member,'manageGuild')))return i.reply({content:'Manage Server permission is required.',flags:64});return i.reply({...await panel(i.guildId),flags:64});}
async function component(i){if(!(await require('./permissionChecker.js').hasPermission(i.member,'manageGuild')))return i.reply({content:'Manage Server permission is required.',flags:64});const id=i.customId;if(id==='whitelist_refresh')return i.update({...await panel(i.guildId),flags:64});if(id==='whitelist_add_user')return i.update({embeds:[new EmbedBuilder().setTitle('Whitelist User').setDescription('Select a user to whitelist.')],components:[new ActionRowBuilder().addComponents(new UserSelectMenuBuilder().setCustomId('whitelist_user_select').setPlaceholder('Select user'))]});if(id==='whitelist_add_role')return i.update({embeds:[new EmbedBuilder().setTitle('Whitelist Role').setDescription('Select a role to whitelist.')],components:[new ActionRowBuilder().addComponents(new RoleSelectMenuBuilder().setCustomId('whitelist_role_select').setPlaceholder('Select role'))]});if(id==='whitelist_remove'){const rows=await WhitelistEntry.find({guildId:i.guildId}).sort({createdAt:-1}).limit(25);if(!rows.length)return i.reply({content:'No whitelist entries exist.',flags:64});return i.update({embeds:[new EmbedBuilder().setTitle('Remove Whitelist Entry').setDescription('Select an entry to remove.')],components:[new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('whitelist_remove_select').setPlaceholder('Select entry').addOptions(rows.map(r=>({label:`${r.type}: ${r.targetId}`.slice(0,100),value:String(r._id)}))))]});}if(id==='whitelist_add_channel')return i.update({embeds:[new EmbedBuilder().setTitle('Whitelist Channel').setDescription('Select a channel to whitelist.')],components:[new ActionRowBuilder().addComponents(new ChannelSelectMenuBuilder().setCustomId('whitelist_channel_select').setPlaceholder('Select channel').setChannelTypes(ChannelType.GuildText,ChannelType.GuildAnnouncement,ChannelType.GuildCategory))]});}
async function select(i){if(!(await require('./permissionChecker.js').hasPermission(i.member,'manageGuild')))return i.reply({content:'Manage Server permission is required.',flags:64});const map={whitelist_user_select:'user',whitelist_role_select:'role',whitelist_channel_select:'channel'};const type=map[i.customId];if(i.customId==='whitelist_remove_select'){await WhitelistEntry.deleteOne({_id:i.values[0],guildId:i.guildId});return i.update({...await panel(i.guildId),flags:64});}if(!type)return;const targetId=i.values[0];await WhitelistEntry.updateOne({guildId:i.guildId,type,targetId},{$setOnInsert:{guildId:i.guildId,type,targetId,addedBy:i.user.id}},{upsert:true});return i.update({...await panel(i.guildId),flags:64});}
function isWhitelisted(guildId,type,targetId){return WhitelistEntry.exists({guildId,type,targetId});}
module.exports={panel,handle,component,select,isWhitelisted};
